<pipeline> ::= <filter> | <filter> <pipeline>
<filter> ::= <attribute> <operator> <value>
<attribute> ::= 'CO' | 'PT08.S1' | 'NMHC' | 'C6H6' | 'PT08.S2' | 'NOx' | 'PT08.S3' | 'NO2' | 'PT08.S4' | 'PT08.S5' | 'T' | 'RH' | 'AH'
<operator> ::= lt | le | gt | ge | eq
<value> ::= <CO_value> | <PT08_S1_value> | <NMHC_value> | <C6H6_value> | <PT08_S2_value> | <NOx_value> | <PT08_S3_value> | <NO2_value> | <PT08_S4_value> | <PT08_S5_value> | <T_value> | <RH_value> | <AH_value>
<CO_value> ::= <CO_intPart> . <CO_fracPart>
<CO_intPart> ::= <digit> | <non_zero_digit> <digit>
<CO_fracPart> ::= <digit> <digit> <digit> <digit>
<PT08_S1_value> ::= <PT08_S1_intPart> . <PT08_S1_fracPart>
<PT08_S1_intPart> ::= <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<PT08_S1_fracPart> ::= <digit> <digit> <digit> <digit>
<NMHC_value> ::= <NMHC_intPart> . <NMHC_fracPart>
<NMHC_intPart> ::= <digit> | <non_zero_digit> <digit> | <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<NMHC_fracPart> ::= <digit> <digit> <digit> <digit>
<C6H6_value> ::= <C6H6_intPart> . <C6H6_fracPart>
<C6H6_intPart> ::= <digit> | <non_zero_digit> <digit>
<C6H6_fracPart> ::= <digit> <digit> <digit> <digit>
<PT08_S2_value> ::= <PT08_S2_intPart> . <PT08_S2_fracPart>
<PT08_S2_intPart> ::= <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<PT08_S2_fracPart> ::= <digit> <digit> <digit> <digit>
<NOx_value> ::= <NOx_intPart> . <NOx_fracPart>
<NOx_intPart> ::= <digit> | <non_zero_digit> <digit> | <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<NOx_fracPart> ::= <digit> <digit> <digit> <digit>
<PT08_S3_value> ::= <PT08_S3_intPart> . <PT08_S3_fracPart>
<PT08_S3_intPart> ::= <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<PT08_S3_fracPart> ::= <digit> <digit> <digit> <digit>
<NO2_value> ::= <NO2_intPart> . <NO2_fracPart>
<NO2_intPart> ::= <digit> | <non_zero_digit> <digit> | <non_zero_digit> <digit> <digit>
<NO2_fracPart> ::= <digit> <digit> <digit> <digit>
<PT08_S4_value> ::= <PT08_S4_intPart> . <PT08_S4_fracPart>
<PT08_S4_intPart> ::= <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<PT08_S4_fracPart> ::= <digit> <digit> <digit> <digit>
<PT08_S5_value> ::= <PT08_S5_intPart> . <PT08_S5_fracPart>
<PT08_S5_intPart> ::= <non_zero_digit> <digit> <digit> | <non_zero_digit> <digit> <digit> <digit>
<PT08_S5_fracPart> ::= <digit> <digit> <digit> <digit>
<T_value> ::= <T_intPart> . <T_fracPart>
<T_intPart> ::= <digit> | <non_zero_digit> <digit>
<T_fracPart> ::= <digit> <digit> <digit> <digit>
<RH_value> ::= <RH_intPart> . <RH_fracPart>
<RH_intPart> ::= <digit> | <non_zero_digit> <digit>
<RH_fracPart> ::= <digit> <digit> <digit> <digit>
<AH_value> ::= <AH_intPart> . <AH_fracPart>
<AH_intPart> ::= <digit>
<AH_fracPart> ::= <digit> <digit> <digit> <digit>
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<non_zero_digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
